version: "3.1"
services:

 api_mariadb:
      image: mariadb:latest
      container_name: api_mariadb
      restart: unless-stopped
      tty: true
      volumes:
       - ./bd/mariadb:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=root-pass
        - MYSQL_DATABASE=hackthon
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
        - TZ=America/Sao_Paulo
      ports:
        - "3306:3306"
      networks:
        - api

networks:
  api:
    driver: bridge

volumes:
  database:
    driver: local